// All UI copy lives here — no hardcoded strings in templates. Persian (fa), RTL.
export const CONTENT = {
  brand: 'دیدار گلد',
  phone: '+982191002020',
  phoneDisplay: '۰۲۱–۹۱۰۰۲۰۲۰',
  email: 'info@didargold.com',
  whatsapp: 'https://wa.me/989120000000',
  telegram: 'https://t.me/didargold',
  instagram: 'https://instagram.com/didargold',

  // Default banner + per-landing overrides (keyed by /l/<slug>).
  promo: 'با خرید +۲۰۰ گرم از کالکشن لوکس، ۱٪ تخفیف روی کل فاکتور',
  promoByLanding: {
    one: 'با خرید +۲۰۰ گرم از کالکشن لوکس، ۱٪ تخفیف روی کل فاکتور',
    two: 'با خرید +۲۰۰ گرم از کالکشن روزمره، ۱٪ تخفیف روی کل فاکتور دریافت کنید',
    three: 'با خرید +۲۰۰ گرم از کالکشن‌ها، ۲٪ تخفیف روی کل فاکتور',
  } as Record<string, string>,

  nav: {
    order: 'سفارش',
    home: 'خانه',
    shop: 'فروشگاه',
    collections: 'کالکشن‌ها',
    verify: 'اصالت‌سنجی',
    account: 'حساب کاربری',
    accountShort: 'حساب',
    cart: 'سبد',
    favorites: 'علاقه‌مندی',
  },

  shop: {
    title: 'فروشگاه دیدار',
    description: 'مجموعه کامل طلای ۱۸ عیار دیدار؛ انتخاب کنید، به سبد بیفزایید و سفارش خود را بدون پرداخت آنلاین ثبت کنید.',
    viewCollection: 'مشاهده کالکشن',
    searchPlaceholder: 'جستجوی محصول…',
    all: 'همه',
    sortLabel: 'مرتب‌سازی',
    // "newest" actually orders by the admin's sort_order — label it honestly.
    sortNewest: 'پیشنهاد دیدار',
    sortWeightAsc: 'سبک‌ترین',
    sortWeightDesc: 'سنگین‌ترین',
    empty: 'محصولی با این فیلترها یافت نشد.',
    resultCount: (n: number) => `${n} محصول`,
    inCart: 'در سبد',
    clearAll: 'پاک کردن همه',
    clearFilters: 'پاک کردن فیلترها',
    searchChip: (q: string) => `«${q}»`,
    // Advanced filter panel
    advancedToggle: 'فیلتر پیشرفته',
    weightLabel: 'وزن (گرم)',
    karatLabel: 'عیار',
    ojratLabel: 'اجرت (٪)',
    minLabel: 'از',
    maxLabel: 'تا',
    weightChip: (min: string, max: string) =>
      `وزن ${min || '۰'}${max ? `–${max}` : '+'} گرم`,
    ojratChip: (min: string, max: string) =>
      `اجرت ${min || '۰'}${max ? `–${max}` : '+'}٪`,
    karatChip: (k: number) => `عیار ${k}`,
    noMatch: 'موردی با این جستجو یافت نشد.',
    categoriesTitle: 'دسته‌بندی‌ها',
    heroEyebrow: 'DIDAR GOLD',
    allProducts: 'همه محصولات',
    catalogEyebrow: 'مجموعه دیدار',
    catalogTitle: 'کاتالوگ محصولات',
    filtersTitle: 'فیلترها',
    applyFilters: 'مشاهده نتایج',
    scrollHint: 'مشاهده محصولات',
    addToCart: 'افزودن به سبد',
    viewAllProducts: 'مشاهده همه محصولات',
    // نرخ روز strip (public TGJU rates)
    goldPriceLabel: 'نرخ لحظه‌ای طلای ۱۸ عیار',
    goldPriceUnit: 'تومان / گرم',
    goldPriceUpdated: (t: string) => `بروزرسانی ${t}`,
    // Trust strip (authenticity / warranty / buyback)
    trustVerify: 'اصالت با کد اختصاصی',
    trustVerifyCta: 'بررسی اصالت',
    trustWarranty: 'گارانتی معتبر دیدار',
    trustBuyback: 'بازخرید شفاف',
  },

  // Order status labels (customer-facing), keyed by OrderStatus.
  orderStatuses: {
    new: 'ثبت شد',
    contacted: 'در حال پیگیری',
    confirmed: 'تأیید شد',
    preparing: 'در حال آماده‌سازی',
    shipped: 'ارسال شد',
    delivered: 'تحویل شد',
    cancelled: 'لغو شد',
  } as Record<string, string>,

  account: {
    // Login (OTP)
    loginTitle: 'ورود / ثبت‌نام',
    loginSubtitle: 'برای ورود به حساب کاربری، شماره موبایل خود را وارد کنید.',
    phone: 'شماره موبایل',
    sendCode: 'ارسال کد',
    sending: 'در حال ارسال…',
    codeSentTo: (phone: string) => `کد تأیید به شماره ${phone} ارسال شد.`,
    code: 'کد تأیید',
    verify: 'ورود',
    verifying: 'در حال بررسی…',
    changePhone: 'ویرایش شماره',
    devCode: (c: string) => `کد تست (فقط در حالت توسعه): ${c}`,
    errBadPhone: 'شماره موبایل معتبر وارد کنید، مثال: ۰۹۱۲۱۲۳۴۵۶۷.',
    errBadCode: 'کد واردشده نادرست یا منقضی شده است.',
    errGeneric: 'خطایی رخ داد. دوباره تلاش کنید.',
    // Panel chrome
    panelTitle: 'حساب کاربری',
    logout: 'خروج',
    tabs: {
      overview: 'خلاصه',
      orders: 'سفارش‌ها',
      favorites: 'علاقه‌مندی‌ها',
      profile: 'پروفایل و آدرس‌ها',
    },
    // Overview
    greeting: (name: string) => `سلام${name ? '، ' + name : ''} 👋`,
    ordersCount: 'سفارش‌ها',
    favoritesCount: 'علاقه‌مندی‌ها',
    lastOrder: 'آخرین سفارش',
    viewAll: 'مشاهده همه',
    // Orders
    ordersTitle: 'سفارش‌های من',
    ordersEmpty: 'هنوز سفارشی ثبت نکرده‌اید.',
    orderedOn: 'تاریخ ثبت',
    orderItems: 'اقلام',
    timeline: 'روند سفارش',
    goShop: 'رفتن به فروشگاه',
    // Favorites
    favoritesTitle: 'علاقه‌مندی‌ها',
    favoritesEmpty: 'فهرست علاقه‌مندی‌های شما خالی است.',
    favAddedToast: 'به علاقه‌مندی‌ها اضافه شد',
    favRemovedToast: 'از علاقه‌مندی‌ها حذف شد',
    // Profile
    profileTitle: 'پروفایل',
    fullName: 'نام و نام خانوادگی',
    save: 'ذخیره',
    saved: 'ذخیره شد.',
    addressesTitle: 'آدرس‌های من',
    addAddress: 'افزودن آدرس',
    addrTitle: 'عنوان (مثل منزل)',
    addrProvince: 'استان',
    addrCity: 'شهر',
    addrLine: 'نشانی کامل',
    addrDefault: 'آدرس پیش‌فرض',
    addressesEmpty: 'هنوز آدرسی ثبت نکرده‌اید.',
    remove: 'حذف',
    edit: 'ویرایش',
    defaultBadge: 'پیش‌فرض',
  },

  hero: {
    eyebrow: 'DIDAR GOLD · LUXURY',
    headline: 'درخشش طلای ناب، از دیدار',
    supporting: 'تأمین‌کننده عمده جواهرات طلا برای فروشگاه‌های معتبر سراسر کشور.',
    cta: 'مشاهده محصولات',
  },

  trust: [
    { title: 'اصالت و ردیابی', sub: 'بر پایه اطلاعات معتبر' },
    { title: 'مسیر گارانتی', sub: 'معرفی پوشش خدمات' },
    { title: 'بررسی بازخرید', sub: 'ورودی درخواست اولیه' },
  ],

  products: {
    eyebrow: 'مجموعه دیدار',
    title: 'محصولات',
    description: 'گزیده‌ای از طرح‌های طلای ۱۸ عیار، آماده برای سفارش عمده فروشگاه‌ها.',
    priceOnRequest: 'استعلام قیمت',
    // Three landing carousels, keyed by product.category.
    daily: {
      eyebrow: 'کالکشن روزمره',
      title: 'طلای روزمره',
      description: 'طرح‌های سبک و کاربردی برای استفاده روزانه، مناسب فروش پرگردش فروشگاه.',
    },
    lux_daily: {
      eyebrow: 'کالکشن لوکس روزمره',
      title: 'طلای لوکس روزمره',
      description: 'طرح‌های روزمره با جلوه‌ای لوکس‌تر؛ حد فاصل کاربردی و خاص.',
    },
    luxury: {
      eyebrow: 'کالکشن لوکس',
      title: 'طلای لوکس',
      description: 'قطعات شاخص و سنگین‌وزن برای مشتریان خاص و ویترین ممتاز فروشگاه.',
    },
    add: 'افزودن به سبد',
    added: 'انتخاب‌شده',
    sample: 'نمونه',
    sampleNote: 'نمونه — غیرقابل سفارش',
    weight: 'وزن',
    karat: 'عیار',
    ojrat: 'اجرت',
    sku: 'کد',
    gram: 'گرم',
    quantity: 'تعداد',
    viewDetails: 'مشاهده جزئیات',
    related: 'محصولات مرتبط',
  },

  cart: {
    title: 'سبد سفارش',
    empty: 'سبد شما خالی است.',
    remove: 'حذف',
    continue: 'ادامه و ثبت سفارش',
    itemsCount: (n: number) => `${n} کالا`,
    total: 'جمع کل',
    addedToast: 'به سبد اضافه شد',
  },

  faq: {
    eyebrow: 'راهنمای خرید',
    title: 'سؤالات متداول',
    description: 'پاسخ روشن به پرسش‌های رایج درباره سفارش، قیمت‌گذاری، ارسال و اصالت طلا.',
  },

  form: {
    title: 'ثبت اطلاعات سفارش',
    summary: 'خلاصه سفارش شما',
    fullName: 'نام و نام خانوادگی',
    phone: 'شماره موبایل',
    storeName: 'نام فروشگاه',
    province: 'استان',
    provincePlaceholder: 'انتخاب استان',
    city: 'شهر (اختیاری)',
    contactMethod: 'روش پیگیری سفارش',
    contactMethods: {
      call: 'تماس مستقیم',
      agent: 'کارشناس فروش',
      whatsapp: 'واتساپ',
    },
    note: 'توضیحات (اختیاری)',
    submit: 'ثبت سفارش',
    submitting: 'در حال ثبت…',
    errors: {
      fullName: 'نام را کامل وارد کنید (بین ۳ تا ۶۰ حرف).',
      phone: 'شماره موبایل معتبر وارد کنید، مثال: ۰۹۱۲۱۲۳۴۵۶۷.',
      storeName: 'نام فروشگاه را وارد کنید (بین ۲ تا ۸۰ حرف).',
      province: 'استان را انتخاب کنید.',
      note: 'توضیحات نباید بیشتر از ۳۰۰ حرف باشد.',
      generic: 'ثبت سفارش با خطا مواجه شد. دوباره تلاش کنید.',
    },
  },

  success: {
    title: 'سفارش شما ثبت شد',
    reference: 'کد پیگیری',
    next: 'کارشناسان ما به‌زودی برای هماهنگی با شما تماس می‌گیرند.',
    call: 'همین حالا تماس بگیرید',
  },

  footer: {
    tagline: 'تأمین‌کننده عمده طلا و جواهرات ۱۸ عیار',
    hoursTitle: 'نشانی و ساعات کاری',
    socialTitle: 'ما را دنبال کنید',
    address: 'تهران، مجتمع دیدار',
    hours: 'شنبه تا چهارشنبه، ۱۰ تا ۱۸',
    rights: 'تمامی حقوق برای دیدار گلد محفوظ است.',
    call: 'تماس تلفنی',
  },
} as const
