// Iran's 31 provinces. `value` mirrors backend app/constants/provinces.py exactly
// (server validates against it); `label` is the Persian name shown to the user.
export const PROVINCES: { value: string; label: string }[] = [
  { value: 'Alborz', label: 'البرز' },
  { value: 'Ardabil', label: 'اردبیل' },
  { value: 'Azerbaijan, East', label: 'آذربایجان شرقی' },
  { value: 'Azerbaijan, West', label: 'آذربایجان غربی' },
  { value: 'Bushehr', label: 'بوشهر' },
  { value: 'Chaharmahal and Bakhtiari', label: 'چهارمحال و بختیاری' },
  { value: 'Fars', label: 'فارس' },
  { value: 'Gilan', label: 'گیلان' },
  { value: 'Golestan', label: 'گلستان' },
  { value: 'Hamadan', label: 'همدان' },
  { value: 'Hormozgan', label: 'هرمزگان' },
  { value: 'Ilam', label: 'ایلام' },
  { value: 'Isfahan', label: 'اصفهان' },
  { value: 'Kerman', label: 'کرمان' },
  { value: 'Kermanshah', label: 'کرمانشاه' },
  { value: 'Khuzestan', label: 'خوزستان' },
  { value: 'Kohgiluyeh and Boyer-Ahmad', label: 'کهگیلویه و بویراحمد' },
  { value: 'Kurdistan', label: 'کردستان' },
  { value: 'Lorestan', label: 'لرستان' },
  { value: 'Markazi', label: 'مرکزی' },
  { value: 'Mazandaran', label: 'مازندران' },
  { value: 'North Khorasan', label: 'خراسان شمالی' },
  { value: 'Qazvin', label: 'قزوین' },
  { value: 'Qom', label: 'قم' },
  { value: 'Razavi Khorasan', label: 'خراسان رضوی' },
  { value: 'Semnan', label: 'سمنان' },
  { value: 'Sistan and Baluchestan', label: 'سیستان و بلوچستان' },
  { value: 'South Khorasan', label: 'خراسان جنوبی' },
  { value: 'Tehran', label: 'تهران' },
  { value: 'Yazd', label: 'یزد' },
  { value: 'Zanjan', label: 'زنجان' },
]
