# Iran's 31 provinces (English). Kept in sync with frontend constants/provinces.ts
IRAN_PROVINCES: list[str] = [
    "Alborz",
    "Ardabil",
    "Azerbaijan, East",
    "Azerbaijan, West",
    "Bushehr",
    "Chaharmahal and Bakhtiari",
    "Fars",
    "Gilan",
    "Golestan",
    "Hamadan",
    "Hormozgan",
    "Ilam",
    "Isfahan",
    "Kerman",
    "Kermanshah",
    "Khuzestan",
    "Kohgiluyeh and Boyer-Ahmad",
    "Kurdistan",
    "Lorestan",
    "Markazi",
    "Mazandaran",
    "North Khorasan",
    "Qazvin",
    "Qom",
    "Razavi Khorasan",
    "Semnan",
    "Sistan and Baluchestan",
    "South Khorasan",
    "Tehran",
    "Yazd",
    "Zanjan",
]
